services:
  web:
    build: 
      context: .
      dockerfile: ./Web/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - .:/code
  mysql:
    image: "mysql:latest"
  azure:
    image: "mcr.microsoft.com/azure-cli"